baseURL: "https://edwardzcn-decade.github.io"
languageCode: 'en-us'
title: "Edwardzcn's Blog"
theme: 'PaperMod'
enableEmoji: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search


params:
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...
  profileMode:
    enabled: false
    title: "Edwardzcn" # optional default will be site title
    subtitle: "Shadow in the dark" # optional
    imageUrl: "favicon.jpg" # optional
    imageTitle: "Favicon" # optional
    imageWidth: 140 # custom size
    imageHeight: 140 # custom size
    buttons:
      - name: Archive
        url: "/archive"
      - name: Github
        url: "https://github.com/edwardzcn-decade"

  socialIcons: # optional
    # - name: "wechat"
    #   url: "https://eddyblog.oss-cn-shenzhen.aliyuncs.com/Blog/wx_qrcode.jpg"
    - name: "email"
      # url: "edwardzcn98@gmail.com"
    - name: "github"
      url: "https://github.com/edwardzcn-decade"
    - name: "telegram"
      url: "<link2>"


  ShowShareButtons: true
  ShowToc: true
  ShowCodeCopyButtons: true
